### ISSUE TITLE
Add dataset error

### ISSUE THREAD

**Issue by SofianeBoumedine** [Inist-CNRS/lodex#1060]
Hi,
Thank's for this project and the differents ressources (Tuts video & doc)

I open this issue because I have an error when I want add a dataset (csv, xcls).
I have check all dataset are in UTF8, but when I want add them I have an error : 
**"L'opération a été annulée à cause d'une erreur/The operation was canceled due to an error"**

After that I test with other files and I have a pop up "Save of dataset" who load indefinitely.

Thank's in advance.

INFO:
We have install lodex correctly with mongodb.

**Comment by SofianeBoumedine** [comment]
Up

**Comment by touv** [comment]
It is absolutely necessary to choose the right parser for the input file, otherwise the application will be blocked. In this case, you have to clean the database and restart the application, this is a known bug.
So if you want to load a CSV file, you have to know the separator and choose the right parser. (see screeshot)
We have already loaded many csv files. It's going to work, I hope so :-)
![image](https://user-images.githubusercontent.com/15609/75346045-22ca9400-589e-11ea-9d52-a70ff0e40750.png)

PS : I answer late, I was on vacation !

**Comment by SofianeBoumedine** [comment]
No prob. Thank's for the response. However I have the same error with XML files

**Comment by touv** [comment]
XML files must be split into documents with a predefined xpath separator. It's more tricky. 

You can find some examples, in a dedicated repositry https://github.com/Inist-CNRS/lodex-use-cases/tree/master/films
