### ISSUE TITLE
Auto-completion for scheme is sometimes sparse

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#149]
When I type `actor` in scheme auto-completed field, I get only two suggestions:

- po:actor
- schema:actor

Searching directly in the LOV, I find [223 items](http://lov.okfn.org/dataset/lov/terms?q=actor).
I would like to get `mrel:act` too in the suggestions, and at least the 10 first results of the query.

> **Note:** I wrote this issue, to separate the main problems of issue #135

**Comment by djhi** [comment]
The strange part is that we are simply calling the `search` method on the lov API. 
See https://github.com/Inist-CNRS/lodex/blob/master/src/app/js/lib/SchemeAutoComplete.js#L77

**Comment by parmentf** [comment]
Yep, strange. 
http://lov.okfn.org/dataset/lov/api/v2/term/search?q=actor returns 10 results. 
Including `mrel:act`. :-/

Oh. Maybe because I use v5.6.0 of lodex? Hmm... No. [5.6.0](https://github.com/Inist-CNRS/lodex/blob/v5.6.0/src/app/js/lib/SchemeAutoComplete.js#L76) uses the same query: http://lov.okfn.org/dataset/lov/api/v2/term/search?q=${query}

**Comment by djhi** [comment]
Trouvé: les résultats sont paginés et par défaut, le service ne renvoie que les 10 premiers

**Comment by djhi** [comment]
Well, the problem is twofold:

- The lov API returns paginated results which we can't handle with the material-ui component currently, so we can only display the first 10 (default lov page size)
- We do receive at least 10 results for the `actor` search and I can see we pass them to the component. However, it only display 3 of them...

We discussed with Nicolas about this and decided it was low priority. You can copy/paste your own URL since version [5.12.1](https://github.com/Inist-CNRS/lodex/releases/tag/v5.12.1) if you can't find it in the auto-completion results.

The scheme completion through complex search (with facets, paginated results, etc.) will eventually be addressed later.

**Comment by touv** [comment]
<blockquote class="trello-card"><a href="https://trello.com/c/XYxuGMV0/98-la-saisie-du-scheme-dun-champ-est-impossible-sans-faire-un-copier-coller-la-compl%C3%A9tion-ne-fonctionne-pas-et-en-plus-elle-perturb">La saisie du scheme d&#39;un champ est impossible sans faire un copier-coller, la complétion ne fonctionne pas et en plus elle perturbe la saisie au clavier</a></blockquote>
