### ISSUE TITLE
NQuads contains only "literal" values

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#381]
![image](https://user-images.githubusercontent.com/15609/27424943-14e9d55a-5737-11e7-9d6e-c9a0282e225a.png)

**Comment by touv** [comment]
http://... => should be an URI <http://...>
ark:/... => should be an internal URI <http:// CURRENT_HOST/ark:/...>
uid:/... => should be an internal UID <http:// CURRENT_HOST/uid:/...>

**Comment by parmentf** [comment]
Note that CURRENT_HOST should not include the version number of ezmaster's instances.

For example: `test-name-1.data.istex.fr` should be `test-name.data.istex.fr`, otherwise the exported data could not be imported within a new instance (say `test-name-2.data.istex.fr`), without modifying the URI.

See #372

**Comment by QuanticPotatoes** [comment]
![image](https://user-images.githubusercontent.com/7420853/28367868-bc153c50-6c92-11e7-9bbe-b54e385eb421.png)
![image](https://user-images.githubusercontent.com/7420853/28367886-c7bc0f16-6c92-11e7-939e-13373aeabc7f.png)

**Comment by parmentf** [comment]
Have been done in `src/api/statements/linkDataset.js`.

Should have been done in [JSONLDObject](https://github.com/Inist-CNRS/lodex/blob/master/src/api/statements/JSONLDObject.js).
