### ISSUE TITLE
add class property beside scheme in the model

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#386]
Example with : https://fr.wikipedia.org/wiki/FOAF
```
   {
        "cover": "collection",
        "label": "Prénom",
        "display_in_list": true,
        "display_in_resource": true,
        "searchable": true,
        "transformers": [
            {
                "operation": "COLUMN",
                "args": [
                    {
                        "name": "column",
                        "type": "column",
                        "value": "dc$identifier"
                    }
                ]
            }
        ],
        "position": 11,
        "scheme": "http://xmlns.com/foaf/spec/#term_lastName",
        "classes" : "http://xmlns.com/foaf/spec/#term_Person"         <<<<<<<<<<<< could be empty or not set
        "format": {
            "name": "None"
        },
        "isFacet": false,
        "name": "OEOA"
    },
```

**Comment by touv** [comment]
value = "Angela Beesley"
scheme = http://xmlns.com/foaf/0.1/name
classes = [
   http://xmlns.com/foaf/0.1/Person 
     http://xmlns.com/foaf/0.1/knows
       http://xmlns.com/foaf/0.1/Person
]

**Comment by touv** [comment]
value=jwales
scheme=http://xmlns.com/foaf/0.1/#accountName
classes= [
http://xmlns.com/foaf/0.1/#account
http://xmlns.com/foaf/0.1/#OnlineAccount
]

**Comment by parmentf** [comment]
Don't forget to add the `Class` field in the Admin interface!
Maybe a new issue?

**Comment by QuanticPotatoes** [comment]
We need to add rdf:type in Triple exports too.
new issue ?

**Comment by parmentf** [comment]
![triplex-semantics-class](https://user-images.githubusercontent.com/595509/28118430-4405e2cc-6711-11e7-9bb9-f3972ec3bad3.jpg)

In backoffice, Semantics part of the wizard, add a `Class` (or better labelled) category, where you can input:
- (required) the class of the pointed property (e.g. `foaf:Person`)
- (optional) the scheme of the pointed property (e.g. `foaf:name`)

In another issue, the value of the `foaf:knows` property will be exported into a blank node, whose property is `foaf:name` (because in tabular data, cells generally contain literal data, not URIs).

In the exception where the cell value is an URI, input the class of the entity (e.g. `foaf:Organization`), and no scheme (because an URI is not a property).

For the resource's class, one can declare it in the `config.json` file of lodex, using `collectionClass` (for example).
